//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GesCom.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        public int Id { get; set; }
        public string Numero { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> QteCommande { get; set; }
        public Nullable<double> Montant { get; set; }
        public Nullable<int> Id_Client { get; set; }
        public string Id_Article { get; set; }
    }
}
